"use client";

// GalaxyAbout — the ONE About/EULA/License surface for every Galaxy app.
//
// CANONICAL COPY: Galaxy-Nexus/packages/galaxy-about/galaxy-about.tsx
// Apps embed a copy of this file (cross-repo imports don't survive each app's
// Docker build context). When editing, edit the canonical copy first, then
// re-sync the app copies — the whole point is that every app shows the same
// thing.
//
// Decisions this file encodes (2026-07-28):
//  - Ownership is a person, not a company: Phan Cao. LinkedIn + CV only —
//    the GitHub link was removed on purpose.
//  - The old deer-flow About (markdown + MCP/Connections tabs) is retired;
//    EULA and License take those slots.
//  - Per-app data (name, version, foundation attribution, dependency list)
//    lives in a sibling `about-data.json`, generated by gen-licenses.mjs —
//    the component itself is app-agnostic.
//
// Self-contained on purpose: React + Tailwind classes only. No shadcn, no
// next-intl, no icon package — so the same file drops into every app
// regardless of its dependency set.

import { useState, type ReactNode } from "react";

export interface GalaxyAboutDep {
  name: string;
  version: string;
  license: string;
}

export interface GalaxyAboutData {
  appId: string;
  appName: string;
  description: string;
  version: string;
  /** Upstream open-source foundation this app builds on, when there is one. */
  foundation?: { name: string; license: string; url?: string; note?: string };
  generatedAt?: string;
  deps: GalaxyAboutDep[];
}

const OWNER = {
  name: "Phan Cao",
  linkedin: "https://www.linkedin.com/in/phancao/",
  cv: "https://phancao.8verse.games/",
};

type SectionId = "about" | "eula" | "license";

const SECTIONS: { id: SectionId; vi: string; en: string }[] = [
  { id: "about", vi: "Giới thiệu", en: "About" },
  { id: "eula", vi: "Điều khoản sử dụng", en: "EULA" },
  { id: "license", vi: "Giấy phép", en: "License" },
];

/* ---------------------------------------------------------------- EULA -- */

const EULA_VI: [string, string][] = [
  [
    "1. Chấp nhận điều khoản",
    "Bằng việc truy cập hoặc sử dụng phần mềm này (“Ứng dụng”), bạn xác nhận đã đọc, hiểu và đồng ý chịu ràng buộc bởi Thỏa thuận cấp phép người dùng cuối này. Nếu không đồng ý, vui lòng ngừng sử dụng Ứng dụng.",
  ],
  [
    "2. Cấp quyền sử dụng",
    "Bạn được cấp quyền sử dụng Ứng dụng — không độc quyền, không chuyển nhượng, có thể thu hồi — cho công việc trong phạm vi tổ chức đã được cấp tài khoản. Quyền này không bao gồm quyền sao chép, phân phối lại, cho thuê, bán hay khai thác thương mại Ứng dụng dưới bất kỳ hình thức nào.",
  ],
  [
    "3. Sở hữu trí tuệ",
    "Ứng dụng, bao gồm mã nguồn, giao diện, nhãn hiệu và tài liệu đi kèm, thuộc sở hữu của Phan Cao. Mọi quyền không được cấp rõ ràng trong thỏa thuận này đều được bảo lưu. Các thành phần mã nguồn mở đi kèm thuộc về tác giả tương ứng và được cấp phép theo giấy phép riêng của chúng (xem mục Giấy phép).",
  ],
  [
    "4. Dữ liệu và quyền riêng tư",
    "Dữ liệu bạn tạo ra trong Ứng dụng thuộc về bạn và tổ chức của bạn. Ứng dụng xử lý dữ liệu trong phạm vi hạ tầng do tổ chức vận hành; các tính năng AI có thể gửi nội dung tới nhà cung cấp mô hình theo cấu hình của quản trị viên. Không sử dụng Ứng dụng để xử lý dữ liệu mà bạn không có quyền xử lý.",
  ],
  [
    "5. Hạn chế",
    "Không được: (a) dịch ngược, phân tích ngược hay trích xuất mã nguồn ngoài phạm vi pháp luật cho phép; (b) vô hiệu hóa các cơ chế bảo mật hoặc kiểm soát truy cập; (c) dùng Ứng dụng cho mục đích vi phạm pháp luật; (d) chia sẻ tài khoản hoặc mã truy cập cho người không được cấp quyền.",
  ],
  [
    "6. Thành phần mã nguồn mở",
    "Ứng dụng sử dụng các thư viện mã nguồn mở được liệt kê tại mục Giấy phép. Việc sử dụng các thành phần đó tuân theo giấy phép gốc của từng thư viện; trường hợp có xung đột giữa thỏa thuận này và giấy phép mã nguồn mở đối với thành phần tương ứng, giấy phép mã nguồn mở được ưu tiên áp dụng cho thành phần đó.",
  ],
  [
    "7. Miễn trừ bảo đảm",
    "Ứng dụng được cung cấp “nguyên trạng” (as is) và “theo khả năng sẵn có”, không kèm bất kỳ bảo đảm nào — rõ ràng hay ngụ ý — về tính thương mại, sự phù hợp cho một mục đích cụ thể, hay việc không xâm phạm. Kết quả do tính năng AI sinh ra có thể không chính xác; bạn chịu trách nhiệm kiểm chứng trước khi sử dụng.",
  ],
  [
    "8. Giới hạn trách nhiệm",
    "Trong phạm vi tối đa pháp luật cho phép, chủ sở hữu không chịu trách nhiệm cho các thiệt hại gián tiếp, ngẫu nhiên, đặc biệt hay hệ quả phát sinh từ việc sử dụng hoặc không thể sử dụng Ứng dụng, kể cả khi đã được thông báo về khả năng xảy ra thiệt hại đó.",
  ],
  [
    "9. Chấm dứt",
    "Quyền sử dụng chấm dứt khi tài khoản của bạn bị thu hồi, khi bạn vi phạm thỏa thuận này, hoặc khi Ứng dụng ngừng cung cấp. Các mục 3, 7, 8 và 10 tiếp tục có hiệu lực sau khi chấm dứt.",
  ],
  [
    "10. Luật áp dụng",
    "Thỏa thuận này được điều chỉnh bởi pháp luật Việt Nam. Tranh chấp phát sinh sẽ được giải quyết trước hết thông qua thương lượng thiện chí.",
  ],
];

const EULA_EN_SUMMARY =
  "English summary: this software is proprietary and owned by Phan Cao. You receive a non-exclusive, non-transferable, revocable right to use it within your organisation. No warranty is provided; AI-generated output must be verified before use. Bundled open-source components remain under their own licenses (see the License section), and those licenses prevail for those components. Vietnamese text above is the governing version.";

/* ------------------------------------------------------------ component -- */

export function GalaxyAbout({
  data,
  logo,
  initialSection = "about",
  fixedSection,
}: {
  data: GalaxyAboutData;
  /** Optional app logo node; falls back to a monogram tile. */
  logo?: ReactNode;
  initialSection?: SectionId;
  /** When the HOST supplies navigation (e.g. a settings sidebar with separate
   *  About/EULA/License entries), pin one section and hide the internal
   *  switcher so there aren't two competing navs. */
  fixedSection?: SectionId;
}) {
  const [section, setSection] = useState<SectionId>(
    fixedSection ?? initialSection,
  );
  const active = fixedSection ?? section;

  return (
    <div className="flex w-full flex-col gap-4 text-sm">
      {/* Header — identical in every app */}
      <div className="flex items-center gap-4">
        {logo ?? (
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-gradient-to-br from-teal-500 to-sky-600 text-xl font-bold text-white">
            {data.appName.replace(/^Galaxy\s+/i, "").charAt(0).toUpperCase()}
          </div>
        )}
        <div className="min-w-0">
          <div className="flex flex-wrap items-baseline gap-2">
            <h2 className="text-lg font-semibold leading-tight">{data.appName}</h2>
            <span className="rounded-full border border-current/20 px-2 py-0.5 text-[11px] opacity-70">
              v{data.version}
            </span>
          </div>
          <p className="mt-0.5 line-clamp-2 opacity-70">{data.description}</p>
        </div>
      </div>

      {/* Section switch — hidden when the host provides its own nav */}
      {!fixedSection && (
        <div className="flex gap-1 rounded-lg bg-black/5 p-1 dark:bg-white/10">
          {SECTIONS.map((s) => (
            <button
              key={s.id}
              type="button"
              onClick={() => setSection(s.id)}
              className={
                "flex-1 rounded-md px-3 py-1.5 text-center transition " +
                (section === s.id
                  ? "bg-white font-medium shadow-sm dark:bg-white/20"
                  : "opacity-60 hover:opacity-90")
              }
            >
              {s.vi}
              <span className="ml-1 text-[10px] uppercase tracking-wide opacity-50">
                {s.en}
              </span>
            </button>
          ))}
        </div>
      )}

      {active === "about" && <AboutSection data={data} />}
      {active === "eula" && <EulaSection />}
      {active === "license" && <LicenseSection data={data} />}
    </div>
  );
}

function AboutSection({ data }: { data: GalaxyAboutData }) {
  return (
    <div className="flex flex-col gap-4">
      <div className="rounded-xl border border-current/10 p-4">
        <div className="text-[11px] font-semibold uppercase tracking-wider opacity-50">
          Quyền sở hữu · Ownership
        </div>
        <div className="mt-1 text-base font-medium">{OWNER.name}</div>
        <div className="mt-3 flex flex-wrap gap-2">
          <a
            href={OWNER.linkedin}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-lg border border-current/15 px-3 py-1.5 transition hover:bg-black/5 dark:hover:bg-white/10"
          >
            LinkedIn
          </a>
          <a
            href={OWNER.cv}
            target="_blank"
            rel="noopener noreferrer"
            className="rounded-lg border border-current/15 px-3 py-1.5 transition hover:bg-black/5 dark:hover:bg-white/10"
          >
            Trang cá nhân / CV
          </a>
        </div>
      </div>

      <div className="rounded-xl border border-current/10 p-4 leading-relaxed opacity-90">
        {data.description}
        {data.foundation && (
          <p className="mt-2 opacity-70">
            Ứng dụng phát triển trên nền{" "}
            {data.foundation.url ? (
              <a
                className="underline underline-offset-2"
                href={data.foundation.url}
                target="_blank"
                rel="noopener noreferrer"
              >
                {data.foundation.name}
              </a>
            ) : (
              data.foundation.name
            )}{" "}
            ({data.foundation.license}).
          </p>
        )}
      </div>

      <p className="text-center text-xs opacity-50">
        © 2026 {OWNER.name}. Bảo lưu mọi quyền · All rights reserved.
      </p>
    </div>
  );
}

function EulaSection() {
  return (
    <div className="max-h-[52vh] overflow-y-auto rounded-xl border border-current/10 p-4">
      <h3 className="font-semibold">
        Thỏa thuận cấp phép người dùng cuối (EULA)
      </h3>
      <p className="mt-1 text-xs opacity-60">
        Áp dụng chung cho mọi ứng dụng thuộc nền tảng Galaxy Vortex.
      </p>
      <div className="mt-3 flex flex-col gap-3 leading-relaxed">
        {EULA_VI.map(([h, body]) => (
          <div key={h}>
            <div className="font-medium">{h}</div>
            <p className="opacity-80">{body}</p>
          </div>
        ))}
        <p className="border-t border-current/10 pt-3 text-xs italic opacity-60">
          {EULA_EN_SUMMARY}
        </p>
      </div>
    </div>
  );
}

function LicenseSection({ data }: { data: GalaxyAboutData }) {
  return (
    <div className="flex max-h-[52vh] flex-col gap-3 overflow-y-auto">
      <div className="rounded-xl border border-current/10 p-4">
        <div className="font-medium">Giấy phép của ứng dụng</div>
        <p className="mt-1 leading-relaxed opacity-80">
          {data.appName} là phần mềm độc quyền. © 2026 {OWNER.name}. Bảo lưu mọi
          quyền. Việc sử dụng tuân theo Điều khoản sử dụng (EULA) của nền tảng.
        </p>
        {data.foundation && (
          <p className="mt-2 leading-relaxed opacity-80">
            Nền tảng gốc: <b>{data.foundation.name}</b> — giấy phép{" "}
            <b>{data.foundation.license}</b>
            {data.foundation.note ? ` (${data.foundation.note})` : ""}. Bản quyền
            phần nền thuộc các tác giả gốc.
          </p>
        )}
      </div>

      <div className="rounded-xl border border-current/10 p-4">
        <div className="font-medium">
          Thư viện mã nguồn mở · Open-source components
        </div>
        <p className="mt-1 text-xs opacity-60">
          Danh sách dependency trực tiếp của ứng dụng này
          {data.generatedAt ? ` (tạo ${data.generatedAt.slice(0, 10)})` : ""}.
          Mỗi thư viện thuộc bản quyền tác giả của nó, theo giấy phép ghi bên
          cạnh.
        </p>
        <table className="mt-2 w-full text-left text-xs">
          <thead>
            <tr className="border-b border-current/10 text-[11px] uppercase tracking-wide opacity-50">
              <th className="py-1 pr-2 font-medium">Thư viện</th>
              <th className="py-1 pr-2 font-medium">Phiên bản</th>
              <th className="py-1 font-medium">Giấy phép</th>
            </tr>
          </thead>
          <tbody>
            {data.deps.map((d) => (
              <tr key={d.name} className="border-b border-current/5">
                <td className="py-1 pr-2 font-mono">{d.name}</td>
                <td className="py-1 pr-2 opacity-70">{d.version}</td>
                <td className="py-1 opacity-70">{d.license}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default GalaxyAbout;
